version: '3'

services:
  todo-dev-env:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.${DOCKER_IMG}
    image: todo-dev-env
    container_name: todo-dev-env
    hostname: ${DOCKER_IMG}
    env_file:
      - ./.env/cache.env
      - ./.env/deploy.env
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - ./.docker/data/shared:/data/shared:rw
      - ./.docker/data/cache:/data/cache:rw
      - ./src:/src:rw
    entrypoint:
      - /bin/bash
      - -c
      - |
        /sbin/init-cache-dir
        tail -f /dev/null

networks:
  default:
    external:
      name: ${APP_NAME}
